// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7S3zedj6miyantm-ZjHQpvcHPgUJSyew',
    appId: '1:729792119936:web:25c804d2c97c4964935265',
    messagingSenderId: '729792119936',
    projectId: 'bugbear-9d720',
    authDomain: 'bugbear-9d720.firebaseapp.com',
    storageBucket: 'bugbear-9d720.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkoYYb1bH949evjRb940gr_OUH7LFnns0',
    appId: '1:729792119936:android:4a0693745974f2e0935265',
    messagingSenderId: '729792119936',
    projectId: 'bugbear-9d720',
    storageBucket: 'bugbear-9d720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAak0nzgDj_ejIu3oc-SHA1Vlrsyg9g74A',
    appId: '1:729792119936:ios:9d68ed97aed03948935265',
    messagingSenderId: '729792119936',
    projectId: 'bugbear-9d720',
    storageBucket: 'bugbear-9d720.firebasestorage.app',
    iosBundleId: 'com.example.bugbearApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAak0nzgDj_ejIu3oc-SHA1Vlrsyg9g74A',
    appId: '1:729792119936:ios:9d68ed97aed03948935265',
    messagingSenderId: '729792119936',
    projectId: 'bugbear-9d720',
    storageBucket: 'bugbear-9d720.firebasestorage.app',
    iosBundleId: 'com.example.bugbearApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7S3zedj6miyantm-ZjHQpvcHPgUJSyew',
    appId: '1:729792119936:web:e90a8cd4d391b79d935265',
    messagingSenderId: '729792119936',
    projectId: 'bugbear-9d720',
    authDomain: 'bugbear-9d720.firebaseapp.com',
    storageBucket: 'bugbear-9d720.firebasestorage.app',
  );
}
