import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'package:flutter/material.dart';
import 'screens/welcome_screen.dart';
import 'screens/login_screen.dart';
import 'screens/timer_screen.dart';
import 'screens/moro_trainer_screen.dart';
import 'screens/training_screen.dart';
import 'screens/spinalergalant_screen.dart';
import 'textt/colors.dart'; // Custom theme

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Login Timer App',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const WelcomeScreen(),
        '/login': (context) => const LoginScreen(),
        '/timer': (context) => const TimerScreen(),
        '/moro': (context) => const MoroTrainerScreen(),
        '/training': (context) => const TrainingScreen(),
        '/spinalergalant': (context) => const SpinalergalantScreen(),
      },
    );
  }
}
