name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: flutter pub get

      - name: Auto-format code
        run: dart format .

      - name: Analyze Project
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run Tests & Gather Coverage
        run: |
          if [ -d test ] && [ "$(ls -A test)" ]; then
            echo "▶ Tests detected — running coverage"
            sudo apt-get update && sudo apt-get install -y lcov
            flutter test --coverage
            lcov --remove coverage/lcov.info 'lib/generated/*' -o coverage/lcov.info
          else
            echo "⚠ No tests found — skipping coverage step"
          fi

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
